{% set name = "geojson-pydantic" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/developmentseed/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 81b2f93030d2e2655fbfd1b662c3e9fa8d1dee98a81ca617587e3baaf7a3b653

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core >=3.2,<4
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=2

test:
  imports:
    - geojson_pydantic
    - geojson_pydantic.base
    - geojson_pydantic.features
    - geojson_pydantic.geometries
    - geojson_pydantic.types
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/developmentseed/geojson-pydantic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pydantic data models for the GeoJSON spec
  # The remaining entries in this section are optional, but recommended.
  description: |
    geojson_pydantic provides a suite of Pydantic models matching the
    GeoJSON specification rfc7946. Those models can be used for creating
    or validating geojson data.
  dev_url: https://github.com/developmentseed/geojson-pydantic

extra:
  recipe-maintainers:
    - ap--
    - martinabeleda
