{% set name = "geojson-pydantic" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/developmentseed/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 5d39ea3c9934f4a190dca67a73ea1fac8e09dc19dfc367ac737a738e4cf21a48

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pydantic

test:
  imports:
    - geojson_pydantic
    - geojson_pydantic.features
    - geojson_pydantic.geometries
    - geojson_pydantic.types
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/developmentseed/geojson-pydantic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pydantic data models for the GeoJSON spec
  # The remaining entries in this section are optional, but recommended.
  description: |
    geojson_pydantic provides a suite of Pydantic models matching the
    GeoJSON specification rfc7946. Those models can be used for creating
    or validating geojson data.
  dev_url: https://github.com/developmentseed/geojson-pydantic

extra:
  recipe-maintainers:
    - ap--
    - martinabeleda
