{% set name = "geojson-pydantic" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/developmentseed/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 8df37ac95af7b9394355f5468a0faa77c93c3eb3569e34af50891c68c8b3607c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=2,<3

test:
  imports:
    - geojson_pydantic
    - geojson_pydantic.base
    - geojson_pydantic.features
    - geojson_pydantic.geometries
    - geojson_pydantic.types
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/developmentseed/geojson-pydantic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pydantic data models for the GeoJSON spec
  # The remaining entries in this section are optional, but recommended.
  description: |
    geojson_pydantic provides a suite of Pydantic models matching the
    GeoJSON specification rfc7946. Those models can be used for creating
    or validating geojson data.
  dev_url: https://github.com/developmentseed/geojson-pydantic

extra:
  recipe-maintainers:
    - ap--
    - martinabeleda
